name: Run JMeter Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-jmeter:
    runs-on: ubuntu-22.04  # Explicitly using Ubuntu 22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: './WebTours_TestPlan_Login1.jmx'
          results-file: result.jtl
 
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error
